#!/bin/bash
cmake -Bbuild -H. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$PREFIX -DPython3_FIND_STRATEGY=LOCATION -DCMAKE_FIND_ROOT_PATH=$PREFIX -DLIMA_ENABLE_PYTHON=1 -DLIMA_ENABLE_CAMERA_TESTS=1
cmake --build build --target install
